apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi-deployment
  labels:
    app: poi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
      - name: poi
        image: registrypiw5325.azurecr.io/poi:2
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: poi
  labels:
    app: poi
spec:
  ports:
  - port: 80
    targetPort: 8081
    protocol: TCP
    name: poi-http
  - port: 443
    targetPort: 8081
    protocol: TCP
    name: poi-https
  selector:
    app: poi
---
apiVersion: v1
kind: Pod
metadata:
  name: poi
  labels:
    purpose: poi-env
spec:
  containers:
  - name: poi-deployment
    image: registrypiw5325.azurecr.io/poi:2
    env:
#    - name: WEB_SERVER_BASE_URI
#      value: ""
#    - name: WEB_PORT
#      value: "80"
#    - name: CONFIG_FILES_PATH
#      value: ""
    - name: SQL_USER
      value: "sqladminpIw5325"
    - name: SQL_PASSWORD
      value: "iN3ls5My6"
    - name: SQL_SERVER
      value: "sqlserverpiw5325"
    - name: SQL_DBNAME
      value: "sqlserverpiw5325/mydrivingDB"
#    - name: ASPNETCORE_ENVIRONMENT
#      value: ""