apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi-deployment
  labels:
    app: poi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
      - name: poi
        image: registrypiw5325.azurecr.io/poi:2
        ports:
        - containerPort: 80
        envFrom:
          - secretRef:
              name: sql
---
apiVersion: v1
kind: Service
metadata:
  name: poi
  labels:
    app: poi
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: poi-http
  - port: 443
    targetPort: 80
    protocol: TCP
    name: poi-https
  selector:
    app: poi
---
apiVersion: v1
kind: Pod
metadata:
  name: poi-env
  labels:
    purpose: poi-envars
spec:
  containers:
  - name: poi
    image: registrypiw5325.azurecr.io/poi:2
    env:
    - name: ASPNETCORE_ENVIRONMENT
      value: "Production"