apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi-deployment
  labels:
    app: poi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
      - name: poi
        image: registrypiw5325.azurecr.io/poi:2
        ports:
        - containerPort: 8081
        envFrom:
          - secretRef:
              name: sql