apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips-deployment
  labels:
    app: trips
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trips
  template:
    metadata:
      labels:
        app: trips
    spec:
      containers:
        - name: trips
          image: 'registrypiw5325.azurecr.io/trips:2'
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: trips-deployment
  labels:
    run: trips
spec:
  ports:
  - port: 8081
    protocol: TCP
  selector:
    run: trips