apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer-deployment
  labels:
    app: tripviewer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      containers:
        - name: tripviewer2
          image: 'registrypiw5325.azurecr.io/tripviewer2:1.0'
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: tripviewer
  labels:
    app: tripviewer
spec:
  ports:
  - protocol: TCP
    port: 80
    name: tripviewer-http
    targetPort: 80
  - protocol: TCP
    port: 443
    name: tripviewer-https
    targetPort: 80
  selector:
    app: tripviewer
---
apiVersion: v1
kind: Pod
metadata:
  name: tripviewer-env
  labels:
    purpose: tripviewer-envars
spec:
  containers:
  - name: tripviewer2
    image: 'registrypiw5325.azurecr.io/tripviewer2:1.0'
    env:
    - name: USERPROFILE_API_ENDPOINT
      value: "http://userprofile.default.svc.cluster.local:80"
    - name: TRIPS_API_ENDPOINT
      value: "http://trips.default.svc.cluster.local:80"
