apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer-deployment
  labels:
    app: tripviewer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      containers:
        - name: tripviewer2
          image: 'registrypiw5325.azurecr.io/tripviewer2:1.0'
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: tripviewer
  labels:
    run: tripviewer
spec:
  ports:
  - port: 8081
    protocol: TCP
  selector:
    run: tripviewer