apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile-deployment
  labels:
    app: userprofile
spec:
  replicas: 3
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      containers:
      - name: userprofile
        image: registrypiw5325.azurecr.io/userprofile:2
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: userprofile
  labels:
    app: userprofile
spec:
  ports:
  - port: 8081
    protocol: TCP
  selector:
    app: userprofile