apiVersion: apps/v1
kind: Deployment
metadata:
  name: userjava-deployment
  labels:
    app: user-java
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-java
  template:
    metadata:
      labels:
        app: user-java
    spec:
      containers:
        - name: user-java
          image: 'registrypiw5325.azurecr.io/user-java:v1'
          ports:
            - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: userjava
  labels:
    app: user-java
spec:
  ports:
  - port: 8081
    protocol: TCP
  selector:
    app: user-java